### ISSUE TITLE
Please support homebrew install

### ISSUE THREAD

**Issue by Alphabet1226** [tisfeng/Easydict#1]

**Comment by Alphabet1226** [comment]
已经很棒了，非常非常喜欢你的作品，加油！第一次开发 Mac 软件就这么高水准真是太厉害了！

**Comment by BingoKingo** [comment]
很棒，从bob社区版来的，希望能够把免费版维护下去，以下是一个模板，稍加修改就可以使用了：
```
cask "easydict" do
  version "1.2.3"
  url "https://github.com/tisfeng/Easydict/releases/download/#{version}/Easydict.dmg"
  #    verified: "github.com/tisfeng/Easydict/"
  sha256 :no_check
  name "Easydict"
  desc "Dictionary and Translator App for looking up words and translating text"
  homepage "https://github.com/tisfeng/Easydict"

  livecheck do
    url "https://github.com/tisfeng/Easydict/releases?q=prerelease%3Afalse"
    regex(%r{href=["']?[^"' >]*?/tree/v?(\d+(?:[.-]\d+)+)?(?:[._-]+?(\d+(?:\.\d+)*))?["' >]}i)
    strategy :page_match do |page, regex|
      page.scan(regex).map do |match|
        (match.length > 1) ? "#{match[0]},#{match[1]}" : match[0]
      end
    end
  end

  auto_updates true

  app "Easydict.app"

  zap trash: [
    "~/Library/Application Support/com.izual.Easydict",
    "~/Library/Caches/com.izual.Easydict",
    "~/Library/HTTPStorages/com.izual.Easydict",
    "~/Library/Preferences/com.izual.Easydict.plist",
  ]
end
```

**Comment by tisfeng** [comment]
非常感谢！我还在想稍后熟悉一下 homebrew，没想到你已经提交 PR 支持了，太好了 🥳

**Comment by ViGeng** [comment]
> 很棒，从bob社区版来的，希望能够把免费版维护下去： [Homebrew/homebrew-cask#141992](https://github.com/Homebrew/homebrew-cask/pull/141992)
> 
> ```
> brew install easydict
> ```

太给力了，正想这么个事儿呢👍 就已经办了

**Comment by Jerry23011** [comment]
刚刚看了一下 brew，如果 Cask 有更新是需要有人去开新的 PR 的

**Comment by tisfeng** [comment]
可以帮忙提去那边供个更新 PR 吗，我观摩一下，之前没弄过这个 🧐

**Comment by Jerry23011** [comment]
> 可以帮忙提去那边供个更新 PR 吗，我观摩一下，之前没弄过这个 🧐

我也是现学的，之前没弄过，还想问问前面的知不知道 😭

**Comment by tisfeng** [comment]
感谢！

**Comment by catch6** [comment]
这完全可以整个 Github action 自动在release 的时候提交 PR给 homebrew 啊，人工维护后面时间成本太高，而且容易漏掉

**Comment by tisfeng** [comment]
这里确实可以用 Github Action 自动化处理，但我对这一块不太熟悉，还在学习阶段，有小伙伴来帮忙一下吗？

**Comment by wytsai7660** [comment]
我想正確的安裝指令應該是 `brew install --cask easydict`，`README.md` 可能需要更新一下。

**Comment by tisfeng** [comment]
感谢，我更新一下。

**Comment by pencilheart** [comment]
目前只能检测到最新版本为2.7.2，但现在出到2.8.0了。

**Comment by pencilheart** [comment]
>来源于chatgpt，不知道可用不？@tisfeng 

要实现一个 GitHub Action，当你发布一个新版本时自动运行 `brew bump --open-pr easydict`，你可以按以下步骤操作：

1. **创建 GitHub Action 配置文件**：

   在你的 GitHub 仓库中，导航到 `.github/workflows/` 目录。如果没有这个目录，可以新建一个。然后在该目录下创建一个 `.yml` 文件，比如 `brew-bump.yml`。

2. **编写 GitHub Action 配置文件**：

   编辑 `brew-bump.yml` 文件，内容可以如下：

   ```yaml
   name: Brew Bump

   on:
     release:
       types: [published]

   jobs:
     brew-bump:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout repository
         uses: actions/checkout@v3

       - name: Set up Homebrew
         run: |
           sudo apt-get update
           sudo apt-get install -y build-essential curl file git
           /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
           echo "eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" >> ~/.bashrc
           eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
           brew install gh

       - name: Bump Homebrew formula
         run: |
           brew bump --open-pr easydict
   ```

   ### 解释：
   - **name**: 设置工作流的名称为 "Brew Bump"。
   - **on**: 配置触发条件。`release` 事件中的 `published` 类型意味着每当你在仓库中发布新版本时，这个 Action 就会触发。
   - **jobs**: 定义要运行的工作，这里我们命名为 `brew-bump`。
   - **runs-on**: 设置 GitHub Action 的运行环境，这里我们选择 `ubuntu-latest`。
   - **steps**: 定义了一系列步骤：
     - `Checkout repository`: 使用 `actions/checkout@v3` 检出仓库代码。
     - `Set up Homebrew`: 安装并配置 Homebrew 环境。
     - `Bump Homebrew formula`: 执行 `brew bump --open-pr easydict` 命令。

3. **推送配置文件到你的仓库**：

   将 `brew-bump.yml` 文件推送到你的 GitHub 仓库。每当你发布新版本时，GitHub Action 将自动运行，并执行 `brew bump --open-pr easydict` 命令。

这样，GitHub Action 将会在你发布新版本时自动运行 `brew bump --open-pr easydict` 命令，并创建一个新的 PR。
